"""
Download the actual atmospheric field from Open-Meteo Historical Weather API.

No synthetic/test weather is generated by this script.

The grid is intentionally moderate for browser use. Increase resolution only
after measuring API response size and browser memory.

Open-Meteo pressure levels are sampled at their native pressure surfaces.
geopotential_height is retained per grid point so the browser can interpolate
to the particle's geometric/geopotential altitude locally.
"""
import json, math, time
from pathlib import Path
import requests

BASE="https://archive-api.open-meteo.com/v1/era5"
LAT_MIN,LAT_MAX=40,70
LON_MIN,LON_MAX=-30,20
GRID_STEP=1.0
START="2010-04-14"
END="2010-04-21"

# Pressure surfaces supported by Open-Meteo ERA5.
LEVELS=[1000,975,950,925,900,850,800,700,600,500,400,300,250,200,150,100,70,50,30]

# API exposes speed/direction. We convert meteorological direction to U/V.
def vars_for(level):
    s=f"{level}hPa"
    return [
      f"wind_speed_{s}",f"wind_direction_{s}",
      f"vertical_velocity_{s}",
      f"temperature_{s}",f"relative_humidity_{s}",
      f"geopotential_height_{s}"
    ]

def grid():
    lats=[];x=LAT_MIN
    while x<=LAT_MAX+1e-9:lats.append(round(x,4));x+=GRID_STEP
    lons=[];x=LON_MIN
    while x<=LON_MAX+1e-9:lons.append(round(x,4));x+=GRID_STEP
    return lats,lons

def chunks(a,n):
    for i in range(0,len(a),n):yield a[i:i+n]

def main():
    lats,lons=grid()
    coords=[(lat,lon) for lat in lats for lon in lons]
    allvars=[v for p in LEVELS for v in vars_for(p)]
    out=[None]*len(coords)

    # Keep batches conservative. Open-Meteo accepts comma-separated coordinates.
    for bi,batch in enumerate(chunks(list(enumerate(coords)),25)):
        latstr=",".join(str(x[1][0]) for x in batch)
        lonstr=",".join(str(x[1][1]) for x in batch)
        params={
          "latitude":latstr,"longitude":lonstr,
          "start_date":START,"end_date":END,
          "hourly":",".join(allvars),
          "timezone":"GMT"
        }
        print(f"batch {bi+1}: {len(batch)} points")
        r=requests.get(BASE,params=params,timeout=120)
        r.raise_for_status()
        data=r.json()
        if isinstance(data,dict): data=[data]
        for (idx,_),item in zip(batch,data):
            out[idx]=item
        time.sleep(0.15)

    # Compact structured representation. The client keeps pressure-level arrays
    # and performs spatial/vertical/time interpolation locally.
    times=out[0]["hourly"]["time"]
    latitudes=lats;longitudes=lons
    nT=len(times);ny=len(lats);nx=len(lons);nk=len(LEVELS)

    def cube():
        return [[[0.0 for _ in range(nx)] for _ in range(ny)] for _ in range(nk)]
    fields={k:[] for k in ["u","v","w","temperature","relativeHumidity","pressure","airDensity"]}
    # JSON is intentionally simple for this first integrated build.
    # Each time contains level->lat->lon arrays.
    for ti in range(nT):
        for name in fields: fields[name].append(cube())

    for idx,item in enumerate(out):
        y=idx//nx;x=idx%nx;h=item["hourly"]
        for ti in range(nT):
            for k,p in enumerate(LEVELS):
                suf=f"{p}hPa"
                sp=h[f"wind_speed_{suf}"][ti]/3.6
                direction=math.radians(h[f"wind_direction_{suf}"][ti])
                # meteorological direction = direction FROM which wind comes
                u=-sp*math.sin(direction);v=-sp*math.cos(direction)
                temp=h[f"temperature_{suf}"][ti]+273.15
                rh=h[f"relative_humidity_{suf}"][ti]
                height=h[f"geopotential_height_{suf}"][ti]
                pressure=p*100.0
                rho=pressure/(287.05*temp)
                fields["u"][ti][k][y][x]=u
                fields["v"][ti][k][y][x]=v
                fields["w"][ti][k][y][x]=h[f"vertical_velocity_{suf}"][ti]/3.6
                fields["temperature"][ti][k][y][x]=temp
                fields["relativeHumidity"][ti][k][y][x]=rh
                fields["pressure"][ti][k][y][x]=pressure
                fields["airDensity"][ti][k][y][x]=rho

    # Heights are required for altitude-aware vertical interpolation.
    heights=[[[0.0 for _ in range(nx)] for _ in range(ny)] for _ in range(nk)]
    for idx,item in enumerate(out):
        y=idx//nx;x=idx%nx;h=item["hourly"]
        for k,p in enumerate(LEVELS):
            heights[k][y][x]=h[f"geopotential_height_{p}hPa"][0]

    payload={
      "source":"Open-Meteo Historical Weather API / ERA5",
      "start":START,"end":END,
      "latitudes":latitudes,"longitudes":longitudes,
      "times":list(range(nT)),
      "pressureLevels":heights,
      **fields,
      "metadata":{"pressure_levels_hPa":LEVELS,"grid_step_deg":GRID_STEP,
                  "time_step_hours":1,"no_synthetic_weather":True}
    }
    Path("data/atmosphere").mkdir(parents=True,exist_ok=True)
    Path("data/atmosphere/open_meteo_grid.json").write_text(json.dumps(payload,separators=(",",":")),encoding="utf8")
    print("Wrote data/atmosphere/open_meteo_grid.json")

if __name__=="__main__":main()
